name: Test PR

on: 
  pull_request:
    branches: 
      - main

jobs:
  pub-get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "Checking PR ..."